// src/utils/generateReportPDF.js
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReportPDF = (analysis) => {
  const doc = new jsPDF();

  // 🏥 Main Header
  doc.setFontSize(20);
  doc.setTextColor(0, 51, 102); // Dark blue
  doc.text("HealthSpectra - Medical Report", 105, 15, { align: "center" });

  // 📄 Patient Info
  const patient = analysis.patientInfo || {};
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Patient Details", 14, 28);

  autoTable(doc, {
    startY: 32,
    head: [["Field", "Value"]],
    body: [
      ["Name", patient.name || "Unknown"],
      ["Age", patient.age || "Unknown"],
      ["Sex", patient.sex || "Unknown"],
      ["Email", patient.email || "Unknown"],
    ],
    theme: "grid",
    styles: { fontSize: 11 },
    headStyles: { fillColor: [0, 51, 102], textColor: 255 }, // Dark header
    alternateRowStyles: { fillColor: [245, 245, 245] }, // subtle gray for alternate rows
  });

  let y = doc.lastAutoTable.finalY + 10;

  // 🧪 Test Results with Symbols and Subtle Colors
  if (analysis.tests && analysis.tests.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(0, 51, 102);
    doc.text("Test Results", 14, y);

    autoTable(doc, {
      startY: y + 5,
      head: [["Test Name", "Result", "Normal Range", "Status", "Explanation"]],
      body: analysis.tests.map((t) => [
        t.testName || "Unknown",
        t.result || "Unknown",
        t.normalRange || "Unknown",
        t.status || "Unknown",
        t.explanation || "Unknown",
      ]),
      theme: "grid",
      styles: { fontSize: 10, cellPadding: 2 },
      headStyles: { fillColor: [0, 51, 102], textColor: 255 },

      // 🎨 Custom colors and symbols for Status
      didParseCell: function (data) {
        if (data.section === "body" && data.column.index === 3) {
          const status = (data.cell.text[0] || "").toLowerCase();
          if (status.includes("high")) {
            data.cell.text[0] = ` ${data.cell.text[0]}`;
            data.cell.styles.textColor = [153, 0, 0]; // dark red
            data.cell.styles.fillColor = [255, 230, 230];
          } else if (status.includes("low")) {
            data.cell.text[0] = ` ${data.cell.text[0]}`;
            data.cell.styles.textColor = [0, 102, 204]; // blue
            data.cell.styles.fillColor = [230, 240, 255];
          } else if (status.includes("elevated") || status.includes("borderline")) {
            data.cell.text[0] = ` ${data.cell.text[0]}`;
            data.cell.styles.textColor = [204, 102, 0]; // orange
            data.cell.styles.fillColor = [255, 245, 220];
          } else if (status.includes("normal")) {
            data.cell.text[0] = `✅ ${data.cell.text[0]}`;
            data.cell.styles.textColor = [0, 153, 51]; // green
            data.cell.styles.fillColor = [230, 255, 230];
          }
        }
      },
    });

    y = doc.lastAutoTable.finalY + 10;
  }

  // 🔹 Helper: Render analysis sections as tables with subtle colors
  const renderSection = (title, data, color = [0, 51, 102]) => {
    if (!data || (Array.isArray(data) && data.length === 0)) return;

    doc.setFontSize(14);
    doc.setTextColor(...color);
    doc.text(title, 14, y);

    const body = Array.isArray(data)
      ? data.map((item, i) => [i + 1, item])
      : [[1, data]];

    autoTable(doc, {
      startY: y + 5,
      head: [["#", "Details"]],
      body,
      theme: "grid",
      styles: { fontSize: 11 },
      headStyles: { fillColor: color, textColor: 255 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    y = doc.lastAutoTable.finalY + 10;
  };

  // 📝 Sections with classic colors
  renderSection("Overall Assessment", analysis.overallAssessment, [0, 51, 102]);
  renderSection("Key Risks", analysis.keyRisks, [153, 0, 0]);
  renderSection("Lifestyle Changes", analysis.lifestyleChanges, [0, 153, 51]);
  renderSection("Recommendations", analysis.recommendations, [102, 0, 153]);
  renderSection("Future Concerns", analysis.futureConcerns, [204, 102, 0]);

  // 🟦 Footer
  const addFooter = () => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(100);

      doc.text("Generated by HealthSpectra", 14, 290);
      doc.text(`Page ${i} of ${pageCount}`, 200, 290, { align: "right" });
    }
  };

  addFooter();

  // Save
  doc.save("Medical_Report.pdf");
};
